name: Release

on:
  push:
    branches:
      - main
      - v2

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build the application
        run: |
          npm run build:browser
          npm run build:node

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx semantic-release
